name: AuthTests

services:

  postgres:
    image: postgres:16
    env_file:
      - ./.env
    volumes:
      - ./database_dump.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app -d auth" ]
      interval: 5s
      timeout: 5s
      retries: 10
    restart: always

  redis:
    image: redis:7.4.1
    command: redis-server --save 60 1 --loglevel warning
    volumes:
      - ./redisdata:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 10

  fastapi-auth:
    build:
      context: .
    image: fastapi
    healthcheck:
      test: curl -s http://fastapi-auth:8000/api/openapi >/dev/null || exit 1
      interval: 5s
      timeout: 5s
      retries: 10
    ports:
      - "8000:8000"
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
